using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevFolio.Models;

namespace DevFolio.Controllers
{
    public class SocialMediaController : Controller
    {

        DbDevFolioEntities db = new DbDevFolioEntities();
        public ActionResult SocialMediaList()
        {
            var values = db.TblSocialMedia.ToList();
            return View(values);
        }

        public ActionResult StatusChangeSocialMedia(int id)
        {
            var value = db.TblSocialMedia.Find(id);
            if(value.Status==true)
            {
                value.Status = false;
            } 
            
            else
            {
                value.Status = true;
            }
            db.SaveChanges();
            return RedirectToAction("SocialMediaList");
        }

        [HttpGet]
        public ActionResult CreateSocialMedia()
        {
            var imageList = new List<SelectListItem>(); 

            imageList.Add(new SelectListItem { Text = "ion-ionic", Value = "ion-ionic" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-up-a", Value = "ion-arrow-up-a" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-right-a", Value = "ion-arrow-right-a" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-down-a", Value = "ion-arrow-down-a" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-left-a", Value = "ion-arrow-left-a" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-up-b", Value = "ion-arrow-up-b" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-right-b", Value = "ion-arrow-right-b" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-down-b", Value = "ion-arrow-down-b" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-left-b", Value = "ion-arrow-left-b" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-up-c", Value = "ion-arrow-up-c" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-right-c", Value = "ion-arrow-right-c" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-down-c", Value = "ion-arrow-down-c" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-left-c", Value = "ion-arrow-left-c" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-return-right", Value = "ion-arrow-return-right" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-return-left", Value = "ion-arrow-return-left" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-swap", Value = "ion-arrow-swap" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-shrink", Value = "ion-arrow-shrink" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-expand", Value = "ion-arrow-expand" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-move", Value = "ion-arrow-move" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-resize", Value = "ion-arrow-resize" });
            imageList.Add(new SelectListItem { Text = "ion-chevron-up", Value = "ion-chevron-up" });
            imageList.Add(new SelectListItem { Text = "ion-chevron-right", Value = "ion-chevron-right" });
            imageList.Add(new SelectListItem { Text = "ion-chevron-down", Value = "ion-chevron-down" });
            imageList.Add(new SelectListItem { Text = "ion-chevron-left", Value = "ion-chevron-left" });
            imageList.Add(new SelectListItem { Text = "ion-navicon-round", Value = "ion-navicon-round" });
            imageList.Add(new SelectListItem { Text = "ion-navicon", Value = "ion-navicon" });
            imageList.Add(new SelectListItem { Text = "ion-drag", Value = "ion-drag" });
            imageList.Add(new SelectListItem { Text = "ion-log-in", Value = "ion-log-in" });
            imageList.Add(new SelectListItem { Text = "ion-log-out", Value = "ion-log-out" });
            imageList.Add(new SelectListItem { Text = "ion-checkmark-round", Value = "ion-checkmark-round" });
            imageList.Add(new SelectListItem { Text = "ion-checkmark", Value = "ion-checkmark" });
            imageList.Add(new SelectListItem { Text = "ion-checkmark-circled", Value = "ion-checkmark-circled" });
            imageList.Add(new SelectListItem { Text = "ion-close-round", Value = "ion-close-round" });
            imageList.Add(new SelectListItem { Text = "ion-close", Value = "ion-close" });
            imageList.Add(new SelectListItem { Text = "ion-close-circled", Value = "ion-close-circled" });
            imageList.Add(new SelectListItem { Text = "ion-plus-round", Value = "ion-plus-round" });
            imageList.Add(new SelectListItem { Text = "ion-plus", Value = "ion-plus" });
            imageList.Add(new SelectListItem { Text = "ion-plus-circled", Value = "ion-plus-circled" });
            imageList.Add(new SelectListItem { Text = "ion-minus-round", Value = "ion-minus-round" });
            imageList.Add(new SelectListItem { Text = "ion-minus", Value = "ion-minus" });
            imageList.Add(new SelectListItem { Text = "ion-minus-circled", Value = "ion-minus-circled" });
            imageList.Add(new SelectListItem { Text = "ion-information", Value = "ion-information" });
            imageList.Add(new SelectListItem { Text = "ion-information-circled", Value = "ion-information-circled" });
            imageList.Add(new SelectListItem { Text = "ion-help", Value = "ion-help" });
            imageList.Add(new SelectListItem { Text = "ion-help-circled", Value = "ion-help-circled" });
            imageList.Add(new SelectListItem { Text = "ion-backspace-outline", Value = "ion-backspace-outline" });
            imageList.Add(new SelectListItem { Text = "ion-backspace", Value = "ion-backspace" });
            imageList.Add(new SelectListItem { Text = "ion-help-buoy", Value = "ion-help-buoy" });
            imageList.Add(new SelectListItem { Text = "ion-asterisk", Value = "ion-asterisk" });
            imageList.Add(new SelectListItem { Text = "ion-alert", Value = "ion-alert" });
            imageList.Add(new SelectListItem { Text = "ion-alert-circled", Value = "ion-alert-circled" });
            imageList.Add(new SelectListItem { Text = "ion-refresh", Value = "ion-refresh" });
            imageList.Add(new SelectListItem { Text = "ion-loop", Value = "ion-loop" });
            imageList.Add(new SelectListItem { Text = "ion-shuffle", Value = "ion-shuffle" });
            imageList.Add(new SelectListItem { Text = "ion-home", Value = "ion-home" });
            imageList.Add(new SelectListItem { Text = "ion-search", Value = "ion-search" });
            imageList.Add(new SelectListItem { Text = "ion-flag", Value = "ion-flag" });
            imageList.Add(new SelectListItem { Text = "ion-star", Value = "ion-star" });
            imageList.Add(new SelectListItem { Text = "ion-heart", Value = "ion-heart" });
            imageList.Add(new SelectListItem { Text = "ion-heart-broken", Value = "ion-heart-broken" });
            imageList.Add(new SelectListItem { Text = "ion-gear-a", Value = "ion-gear-a" });
            imageList.Add(new SelectListItem { Text = "ion-gear-b", Value = "ion-gear-b" });
            imageList.Add(new SelectListItem { Text = "ion-toggle-filled", Value = "ion-toggle-filled" });
            imageList.Add(new SelectListItem { Text = "ion-toggle", Value = "ion-toggle" });
            imageList.Add(new SelectListItem { Text = "ion-settings", Value = "ion-settings" });
            imageList.Add(new SelectListItem { Text = "ion-wrench", Value = "ion-wrench" });
            imageList.Add(new SelectListItem { Text = "ion-hammer", Value = "ion-hammer" });
            imageList.Add(new SelectListItem { Text = "ion-edit", Value = "ion-edit" });
            imageList.Add(new SelectListItem { Text = "ion-trash-a", Value = "ion-trash-a" });
            imageList.Add(new SelectListItem { Text = "ion-trash-b", Value = "ion-trash-b" });
            imageList.Add(new SelectListItem { Text = "ion-document", Value = "ion-document" });
            imageList.Add(new SelectListItem { Text = "ion-document-text", Value = "ion-document-text" });
            imageList.Add(new SelectListItem { Text = "ion-clipboard", Value = "ion-clipboard" });
            imageList.Add(new SelectListItem { Text = "ion-scissors", Value = "ion-scissors" });
            imageList.Add(new SelectListItem { Text = "ion-funnel", Value = "ion-funnel" });
            imageList.Add(new SelectListItem { Text = "ion-bookmark", Value = "ion-bookmark" });
            imageList.Add(new SelectListItem { Text = "ion-email", Value = "ion-email" });
            imageList.Add(new SelectListItem { Text = "ion-email-unread", Value = "ion-email-unread" });
            imageList.Add(new SelectListItem { Text = "ion-folder", Value = "ion-folder" });
            imageList.Add(new SelectListItem { Text = "ion-filing", Value = "ion-filing" });
            imageList.Add(new SelectListItem { Text = "ion-archive", Value = "ion-archive" });
            imageList.Add(new SelectListItem { Text = "ion-reply", Value = "ion-reply" });
            imageList.Add(new SelectListItem { Text = "ion-reply-all", Value = "ion-reply-all" });
            imageList.Add(new SelectListItem { Text = "ion-forward", Value = "ion-forward" });
            imageList.Add(new SelectListItem { Text = "ion-share", Value = "ion-share" });
            imageList.Add(new SelectListItem { Text = "ion-paper-airplane", Value = "ion-paper-airplane" });
            imageList.Add(new SelectListItem { Text = "ion-link", Value = "ion-link" });
            imageList.Add(new SelectListItem { Text = "ion-paperclip", Value = "ion-paperclip" });
            imageList.Add(new SelectListItem { Text = "ion-compose", Value = "ion-compose" });
            imageList.Add(new SelectListItem { Text = "ion-briefcase", Value = "ion-briefcase" });
            imageList.Add(new SelectListItem { Text = "ion-medkit", Value = "ion-medkit" });
            imageList.Add(new SelectListItem { Text = "ion-at", Value = "ion-at" });
            imageList.Add(new SelectListItem { Text = "ion-pound", Value = "ion-pound" });
            imageList.Add(new SelectListItem { Text = "ion-quote", Value = "ion-quote" });
            imageList.Add(new SelectListItem { Text = "ion-cloud", Value = "ion-cloud" });
            imageList.Add(new SelectListItem { Text = "ion-upload", Value = "ion-upload" });
            imageList.Add(new SelectListItem { Text = "ion-more", Value = "ion-more" });
            imageList.Add(new SelectListItem { Text = "ion-grid", Value = "ion-grid" });
            imageList.Add(new SelectListItem { Text = "ion-calendar", Value = "ion-calendar" });
            imageList.Add(new SelectListItem { Text = "ion-clock", Value = "ion-clock" });
            imageList.Add(new SelectListItem { Text = "ion-compass", Value = "ion-compass" });
            imageList.Add(new SelectListItem { Text = "ion-pinpoint", Value = "ion-pinpoint" });
            imageList.Add(new SelectListItem { Text = "ion-pin", Value = "ion-pin" });
            imageList.Add(new SelectListItem { Text = "ion-navigate", Value = "ion-navigate" });
            imageList.Add(new SelectListItem { Text = "ion-location", Value = "ion-location" });
            imageList.Add(new SelectListItem { Text = "ion-map", Value = "ion-map" });
            imageList.Add(new SelectListItem { Text = "ion-lock-combination", Value = "ion-lock-combination" });
            imageList.Add(new SelectListItem { Text = "ion-locked", Value = "ion-locked" });
            imageList.Add(new SelectListItem { Text = "ion-unlocked", Value = "ion-unlocked" });
            imageList.Add(new SelectListItem { Text = "ion-key", Value = "ion-key" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-graph-up-right", Value = "ion-arrow-graph-up-right" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-graph-down-right", Value = "ion-arrow-graph-down-right" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-graph-up-left", Value = "ion-arrow-graph-up-left" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-graph-down-left", Value = "ion-arrow-graph-down-left" });
            imageList.Add(new SelectListItem { Text = "ion-stats-bars", Value = "ion-stats-bars" });
            imageList.Add(new SelectListItem { Text = "ion-connection-bars", Value = "ion-connection-bars" });
            imageList.Add(new SelectListItem { Text = "ion-pie-graph", Value = "ion-pie-graph" });
            imageList.Add(new SelectListItem { Text = "ion-chatbubble", Value = "ion-chatbubble" });
            imageList.Add(new SelectListItem { Text = "ion-chatbubble-working", Value = "ion-chatbubble-working" });
            imageList.Add(new SelectListItem { Text = "ion-chatbubbles", Value = "ion-chatbubbles" });
            imageList.Add(new SelectListItem { Text = "ion-chatbox", Value = "ion-chatbox" });
            imageList.Add(new SelectListItem { Text = "ion-chatbox-working", Value = "ion-chatbox-working" });
            imageList.Add(new SelectListItem { Text = "ion-chatboxes", Value = "ion-chatboxes" });
            imageList.Add(new SelectListItem { Text = "ion-person", Value = "ion-person" });
            imageList.Add(new SelectListItem { Text = "ion-person-add", Value = "ion-person-add" });
            imageList.Add(new SelectListItem { Text = "ion-person-stalker", Value = "ion-person-stalker" });
            imageList.Add(new SelectListItem { Text = "ion-woman", Value = "ion-woman" });
            imageList.Add(new SelectListItem { Text = "ion-man", Value = "ion-man" });
            imageList.Add(new SelectListItem { Text = "ion-female", Value = "ion-female" });
            imageList.Add(new SelectListItem { Text = "ion-male", Value = "ion-male" });
            imageList.Add(new SelectListItem { Text = "ion-transgender", Value = "ion-transgender" });
            imageList.Add(new SelectListItem { Text = "ion-fork", Value = "ion-fork" });
            imageList.Add(new SelectListItem { Text = "ion-knife", Value = "ion-knife" });
            imageList.Add(new SelectListItem { Text = "ion-spoon", Value = "ion-spoon" });
            imageList.Add(new SelectListItem { Text = "ion-soup-can-outline", Value = "ion-soup-can-outline" });
            imageList.Add(new SelectListItem { Text = "ion-soup-can", Value = "ion-soup-can" });
            imageList.Add(new SelectListItem { Text = "ion-beer", Value = "ion-beer" });
            imageList.Add(new SelectListItem { Text = "ion-wineglass", Value = "ion-wineglass" });
            imageList.Add(new SelectListItem { Text = "ion-coffee", Value = "ion-coffee" });
            imageList.Add(new SelectListItem { Text = "ion-icecream", Value = "ion-icecream" });
            imageList.Add(new SelectListItem { Text = "ion-pizza", Value = "ion-pizza" });
            imageList.Add(new SelectListItem { Text = "ion-power", Value = "ion-power" });
            imageList.Add(new SelectListItem { Text = "ion-mouse", Value = "ion-mouse" });
            imageList.Add(new SelectListItem { Text = "ion-battery-full", Value = "ion-battery-full" });
            imageList.Add(new SelectListItem { Text = "ion-battery-half", Value = "ion-battery-half" });
            imageList.Add(new SelectListItem { Text = "ion-battery-low", Value = "ion-battery-low" });
            imageList.Add(new SelectListItem { Text = "ion-battery-empty", Value = "ion-battery-empty" });
            imageList.Add(new SelectListItem { Text = "ion-battery-charging", Value = "ion-battery-charging" });
            imageList.Add(new SelectListItem { Text = "ion-wifi", Value = "ion-wifi" });
            imageList.Add(new SelectListItem { Text = "ion-bluetooth", Value = "ion-bluetooth" });
            imageList.Add(new SelectListItem { Text = "ion-calculator", Value = "ion-calculator" });
            imageList.Add(new SelectListItem { Text = "ion-camera", Value = "ion-camera" });
            imageList.Add(new SelectListItem { Text = "ion-eye", Value = "ion-eye" });
            imageList.Add(new SelectListItem { Text = "ion-eye-disabled", Value = "ion-eye-disabled" });
            imageList.Add(new SelectListItem { Text = "ion-flash", Value = "ion-flash" });
            imageList.Add(new SelectListItem { Text = "ion-flash-off", Value = "ion-flash-off" });
            imageList.Add(new SelectListItem { Text = "ion-qr-scanner", Value = "ion-qr-scanner" });
            imageList.Add(new SelectListItem { Text = "ion-image", Value = "ion-image" });
            imageList.Add(new SelectListItem { Text = "ion-images", Value = "ion-images" });
            imageList.Add(new SelectListItem { Text = "ion-wand", Value = "ion-wand" });
            imageList.Add(new SelectListItem { Text = "ion-contrast", Value = "ion-contrast" });
            imageList.Add(new SelectListItem { Text = "ion-aperture", Value = "ion-aperture" });
            imageList.Add(new SelectListItem { Text = "ion-crop", Value = "ion-crop" });
            imageList.Add(new SelectListItem { Text = "ion-easel", Value = "ion-easel" });
            imageList.Add(new SelectListItem { Text = "ion-paintbrush", Value = "ion-paintbrush" });
            imageList.Add(new SelectListItem { Text = "ion-paintbucket", Value = "ion-paintbucket" });
            imageList.Add(new SelectListItem { Text = "ion-monitor", Value = "ion-monitor" });
            imageList.Add(new SelectListItem { Text = "ion-laptop", Value = "ion-laptop" });
            imageList.Add(new SelectListItem { Text = "ion-ipad", Value = "ion-ipad" });
            imageList.Add(new SelectListItem { Text = "ion-iphone", Value = "ion-iphone" });
            imageList.Add(new SelectListItem { Text = "ion-ipod", Value = "ion-ipod" });
            imageList.Add(new SelectListItem { Text = "ion-printer", Value = "ion-printer" });
            imageList.Add(new SelectListItem { Text = "ion-usb", Value = "ion-usb" });
            imageList.Add(new SelectListItem { Text = "ion-outlet", Value = "ion-outlet" });
            imageList.Add(new SelectListItem { Text = "ion-bug", Value = "ion-bug" });
            imageList.Add(new SelectListItem { Text = "ion-code", Value = "ion-code" });
            imageList.Add(new SelectListItem { Text = "ion-code-working", Value = "ion-code-working" });
            imageList.Add(new SelectListItem { Text = "ion-code-download", Value = "ion-code-download" });
            imageList.Add(new SelectListItem { Text = "ion-fork-repo", Value = "ion-fork-repo" });
            imageList.Add(new SelectListItem { Text = "ion-network", Value = "ion-network" });
            imageList.Add(new SelectListItem { Text = "ion-pull-request", Value = "ion-pull-request" });
            imageList.Add(new SelectListItem { Text = "ion-merge", Value = "ion-merge" });
            imageList.Add(new SelectListItem { Text = "ion-xbox", Value = "ion-xbox" });
            imageList.Add(new SelectListItem { Text = "ion-playstation", Value = "ion-playstation" });
            imageList.Add(new SelectListItem { Text = "ion-steam", Value = "ion-steam" });
            imageList.Add(new SelectListItem { Text = "ion-closed-captioning", Value = "ion-closed-captioning" });
            imageList.Add(new SelectListItem { Text = "ion-videocamera", Value = "ion-videocamera" });
            imageList.Add(new SelectListItem { Text = "ion-film-marker", Value = "ion-film-marker" });
            imageList.Add(new SelectListItem { Text = "ion-disc", Value = "ion-disc" });
            imageList.Add(new SelectListItem { Text = "ion-headphone", Value = "ion-headphone" });
            imageList.Add(new SelectListItem { Text = "ion-music-note", Value = "ion-music-note" });
            imageList.Add(new SelectListItem { Text = "ion-radio-waves", Value = "ion-radio-waves" });
            imageList.Add(new SelectListItem { Text = "ion-speakerphone", Value = "ion-speakerphone" });
            imageList.Add(new SelectListItem { Text = "ion-mic-a", Value = "ion-mic-a" });
            imageList.Add(new SelectListItem { Text = "ion-mic-b", Value = "ion-mic-b" });
            imageList.Add(new SelectListItem { Text = "ion-mic-c", Value = "ion-mic-c" });
            imageList.Add(new SelectListItem { Text = "ion-volume-high", Value = "ion-volume-high" });
            imageList.Add(new SelectListItem { Text = "ion-volume-medium", Value = "ion-volume-medium" });
            imageList.Add(new SelectListItem { Text = "ion-volume-low", Value = "ion-volume-low" });
            imageList.Add(new SelectListItem { Text = "ion-volume-mute", Value = "ion-volume-mute" });
            imageList.Add(new SelectListItem { Text = "ion-levels", Value = "ion-levels" });
            imageList.Add(new SelectListItem { Text = "ion-play", Value = "ion-play" });
            imageList.Add(new SelectListItem { Text = "ion-pause", Value = "ion-pause" });
            imageList.Add(new SelectListItem { Text = "ion-stop", Value = "ion-stop" });
            imageList.Add(new SelectListItem { Text = "ion-record", Value = "ion-record" });
            imageList.Add(new SelectListItem { Text = "ion-skip-forward", Value = "ion-skip-forward" });
            imageList.Add(new SelectListItem { Text = "ion-skip-backward", Value = "ion-skip-backward" });
            imageList.Add(new SelectListItem { Text = "ion-eject", Value = "ion-eject" });
            imageList.Add(new SelectListItem { Text = "ion-bag", Value = "ion-bag" });
            imageList.Add(new SelectListItem { Text = "ion-card", Value = "ion-card" });
            imageList.Add(new SelectListItem { Text = "ion-cash", Value = "ion-cash" });
            imageList.Add(new SelectListItem { Text = "ion-pricetag", Value = "ion-pricetag" });
            imageList.Add(new SelectListItem { Text = "ion-pricetags", Value = "ion-pricetags" });
            imageList.Add(new SelectListItem { Text = "ion-thumbsup", Value = "ion-thumbsup" });
            imageList.Add(new SelectListItem { Text = "ion-thumbsdown", Value = "ion-thumbsdown" });
            imageList.Add(new SelectListItem { Text = "ion-happy-outline", Value = "ion-happy-outline" });
            imageList.Add(new SelectListItem { Text = "ion-happy", Value = "ion-happy" });
            imageList.Add(new SelectListItem { Text = "ion-sad-outline", Value = "ion-sad-outline" });
            imageList.Add(new SelectListItem { Text = "ion-sad", Value = "ion-sad" });
            imageList.Add(new SelectListItem { Text = "ion-bowtie", Value = "ion-bowtie" });
            imageList.Add(new SelectListItem { Text = "ion-tshirt-outline", Value = "ion-tshirt-outline" });
            imageList.Add(new SelectListItem { Text = "ion-tshirt", Value = "ion-tshirt" });
            imageList.Add(new SelectListItem { Text = "ion-trophy", Value = "ion-trophy" });
            imageList.Add(new SelectListItem { Text = "ion-podium", Value = "ion-podium" });
            imageList.Add(new SelectListItem { Text = "ion-ribbon-a", Value = "ion-ribbon-a" });
            imageList.Add(new SelectListItem { Text = "ion-ribbon-b", Value = "ion-ribbon-b" });
            imageList.Add(new SelectListItem { Text = "ion-university", Value = "ion-university" });
            imageList.Add(new SelectListItem { Text = "ion-magnet", Value = "ion-magnet" });
            imageList.Add(new SelectListItem { Text = "ion-beaker", Value = "ion-beaker" });
            imageList.Add(new SelectListItem { Text = "ion-erlenmeyer-flask", Value = "ion-erlenmeyer-flask" });
            imageList.Add(new SelectListItem { Text = "ion-egg", Value = "ion-egg" });
            imageList.Add(new SelectListItem { Text = "ion-earth", Value = "ion-earth" });
            imageList.Add(new SelectListItem { Text = "ion-planet", Value = "ion-planet" });
            imageList.Add(new SelectListItem { Text = "ion-lightbulb", Value = "ion-lightbulb" });
            imageList.Add(new SelectListItem { Text = "ion-cube", Value = "ion-cube" });
            imageList.Add(new SelectListItem { Text = "ion-leaf", Value = "ion-leaf" });
            imageList.Add(new SelectListItem { Text = "ion-waterdrop", Value = "ion-waterdrop" });
            imageList.Add(new SelectListItem { Text = "ion-flame", Value = "ion-flame" });
            imageList.Add(new SelectListItem { Text = "ion-fireball", Value = "ion-fireball" });
            imageList.Add(new SelectListItem { Text = "ion-bonfire", Value = "ion-bonfire" });
            imageList.Add(new SelectListItem { Text = "ion-umbrella", Value = "ion-umbrella" });
            imageList.Add(new SelectListItem { Text = "ion-nuclear", Value = "ion-nuclear" });
            imageList.Add(new SelectListItem { Text = "ion-no-smoking", Value = "ion-no-smoking" });
            imageList.Add(new SelectListItem { Text = "ion-thermometer", Value = "ion-thermometer" });
            imageList.Add(new SelectListItem { Text = "ion-speedometer", Value = "ion-speedometer" });
            imageList.Add(new SelectListItem { Text = "ion-model-s", Value = "ion-model-s" });
            imageList.Add(new SelectListItem { Text = "ion-plane", Value = "ion-plane" });
            imageList.Add(new SelectListItem { Text = "ion-jet", Value = "ion-jet" });
            imageList.Add(new SelectListItem { Text = "ion-load-a", Value = "ion-load-a" });
            imageList.Add(new SelectListItem { Text = "ion-load-b", Value = "ion-load-b" });
            imageList.Add(new SelectListItem { Text = "ion-load-c", Value = "ion-load-c" });
            imageList.Add(new SelectListItem { Text = "ion-load-d", Value = "ion-load-d" });

            ViewBag.imageList = imageList;
            return View();
        }

        [HttpPost]
        public ActionResult CreateSocialMedia(TblSocialMedia p)
        {
            p.Status = true;
            db.TblSocialMedia.Add(p);
            db.SaveChanges();
            return RedirectToAction("SocialMediaList");
        }

        public ActionResult DeleteSocialMedia(int id)
        {
            var value = db.TblSocialMedia.Find(id);
            db.TblSocialMedia.Remove(value);
            db.SaveChanges();
            return RedirectToAction("SocialMediaList");
        }

        [HttpGet]
        public ActionResult UpdateSocialMedia(int id)
        {
            var value = db.TblSocialMedia.Find(id);
            var imageList = new List<SelectListItem>();

            imageList.Add(new SelectListItem { Text = "ion-ionic", Value = "ion-ionic" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-up-a", Value = "ion-arrow-up-a" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-right-a", Value = "ion-arrow-right-a" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-down-a", Value = "ion-arrow-down-a" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-left-a", Value = "ion-arrow-left-a" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-up-b", Value = "ion-arrow-up-b" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-right-b", Value = "ion-arrow-right-b" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-down-b", Value = "ion-arrow-down-b" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-left-b", Value = "ion-arrow-left-b" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-up-c", Value = "ion-arrow-up-c" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-right-c", Value = "ion-arrow-right-c" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-down-c", Value = "ion-arrow-down-c" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-left-c", Value = "ion-arrow-left-c" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-return-right", Value = "ion-arrow-return-right" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-return-left", Value = "ion-arrow-return-left" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-swap", Value = "ion-arrow-swap" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-shrink", Value = "ion-arrow-shrink" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-expand", Value = "ion-arrow-expand" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-move", Value = "ion-arrow-move" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-resize", Value = "ion-arrow-resize" });
            imageList.Add(new SelectListItem { Text = "ion-chevron-up", Value = "ion-chevron-up" });
            imageList.Add(new SelectListItem { Text = "ion-chevron-right", Value = "ion-chevron-right" });
            imageList.Add(new SelectListItem { Text = "ion-chevron-down", Value = "ion-chevron-down" });
            imageList.Add(new SelectListItem { Text = "ion-chevron-left", Value = "ion-chevron-left" });
            imageList.Add(new SelectListItem { Text = "ion-navicon-round", Value = "ion-navicon-round" });
            imageList.Add(new SelectListItem { Text = "ion-navicon", Value = "ion-navicon" });
            imageList.Add(new SelectListItem { Text = "ion-drag", Value = "ion-drag" });
            imageList.Add(new SelectListItem { Text = "ion-log-in", Value = "ion-log-in" });
            imageList.Add(new SelectListItem { Text = "ion-log-out", Value = "ion-log-out" });
            imageList.Add(new SelectListItem { Text = "ion-checkmark-round", Value = "ion-checkmark-round" });
            imageList.Add(new SelectListItem { Text = "ion-checkmark", Value = "ion-checkmark" });
            imageList.Add(new SelectListItem { Text = "ion-checkmark-circled", Value = "ion-checkmark-circled" });
            imageList.Add(new SelectListItem { Text = "ion-close-round", Value = "ion-close-round" });
            imageList.Add(new SelectListItem { Text = "ion-close", Value = "ion-close" });
            imageList.Add(new SelectListItem { Text = "ion-close-circled", Value = "ion-close-circled" });
            imageList.Add(new SelectListItem { Text = "ion-plus-round", Value = "ion-plus-round" });
            imageList.Add(new SelectListItem { Text = "ion-plus", Value = "ion-plus" });
            imageList.Add(new SelectListItem { Text = "ion-plus-circled", Value = "ion-plus-circled" });
            imageList.Add(new SelectListItem { Text = "ion-minus-round", Value = "ion-minus-round" });
            imageList.Add(new SelectListItem { Text = "ion-minus", Value = "ion-minus" });
            imageList.Add(new SelectListItem { Text = "ion-minus-circled", Value = "ion-minus-circled" });
            imageList.Add(new SelectListItem { Text = "ion-information", Value = "ion-information" });
            imageList.Add(new SelectListItem { Text = "ion-information-circled", Value = "ion-information-circled" });
            imageList.Add(new SelectListItem { Text = "ion-help", Value = "ion-help" });
            imageList.Add(new SelectListItem { Text = "ion-help-circled", Value = "ion-help-circled" });
            imageList.Add(new SelectListItem { Text = "ion-backspace-outline", Value = "ion-backspace-outline" });
            imageList.Add(new SelectListItem { Text = "ion-backspace", Value = "ion-backspace" });
            imageList.Add(new SelectListItem { Text = "ion-help-buoy", Value = "ion-help-buoy" });
            imageList.Add(new SelectListItem { Text = "ion-asterisk", Value = "ion-asterisk" });
            imageList.Add(new SelectListItem { Text = "ion-alert", Value = "ion-alert" });
            imageList.Add(new SelectListItem { Text = "ion-alert-circled", Value = "ion-alert-circled" });
            imageList.Add(new SelectListItem { Text = "ion-refresh", Value = "ion-refresh" });
            imageList.Add(new SelectListItem { Text = "ion-loop", Value = "ion-loop" });
            imageList.Add(new SelectListItem { Text = "ion-shuffle", Value = "ion-shuffle" });
            imageList.Add(new SelectListItem { Text = "ion-home", Value = "ion-home" });
            imageList.Add(new SelectListItem { Text = "ion-search", Value = "ion-search" });
            imageList.Add(new SelectListItem { Text = "ion-flag", Value = "ion-flag" });
            imageList.Add(new SelectListItem { Text = "ion-star", Value = "ion-star" });
            imageList.Add(new SelectListItem { Text = "ion-heart", Value = "ion-heart" });
            imageList.Add(new SelectListItem { Text = "ion-heart-broken", Value = "ion-heart-broken" });
            imageList.Add(new SelectListItem { Text = "ion-gear-a", Value = "ion-gear-a" });
            imageList.Add(new SelectListItem { Text = "ion-gear-b", Value = "ion-gear-b" });
            imageList.Add(new SelectListItem { Text = "ion-toggle-filled", Value = "ion-toggle-filled" });
            imageList.Add(new SelectListItem { Text = "ion-toggle", Value = "ion-toggle" });
            imageList.Add(new SelectListItem { Text = "ion-settings", Value = "ion-settings" });
            imageList.Add(new SelectListItem { Text = "ion-wrench", Value = "ion-wrench" });
            imageList.Add(new SelectListItem { Text = "ion-hammer", Value = "ion-hammer" });
            imageList.Add(new SelectListItem { Text = "ion-edit", Value = "ion-edit" });
            imageList.Add(new SelectListItem { Text = "ion-trash-a", Value = "ion-trash-a" });
            imageList.Add(new SelectListItem { Text = "ion-trash-b", Value = "ion-trash-b" });
            imageList.Add(new SelectListItem { Text = "ion-document", Value = "ion-document" });
            imageList.Add(new SelectListItem { Text = "ion-document-text", Value = "ion-document-text" });
            imageList.Add(new SelectListItem { Text = "ion-clipboard", Value = "ion-clipboard" });
            imageList.Add(new SelectListItem { Text = "ion-scissors", Value = "ion-scissors" });
            imageList.Add(new SelectListItem { Text = "ion-funnel", Value = "ion-funnel" });
            imageList.Add(new SelectListItem { Text = "ion-bookmark", Value = "ion-bookmark" });
            imageList.Add(new SelectListItem { Text = "ion-email", Value = "ion-email" });
            imageList.Add(new SelectListItem { Text = "ion-email-unread", Value = "ion-email-unread" });
            imageList.Add(new SelectListItem { Text = "ion-folder", Value = "ion-folder" });
            imageList.Add(new SelectListItem { Text = "ion-filing", Value = "ion-filing" });
            imageList.Add(new SelectListItem { Text = "ion-archive", Value = "ion-archive" });
            imageList.Add(new SelectListItem { Text = "ion-reply", Value = "ion-reply" });
            imageList.Add(new SelectListItem { Text = "ion-reply-all", Value = "ion-reply-all" });
            imageList.Add(new SelectListItem { Text = "ion-forward", Value = "ion-forward" });
            imageList.Add(new SelectListItem { Text = "ion-share", Value = "ion-share" });
            imageList.Add(new SelectListItem { Text = "ion-paper-airplane", Value = "ion-paper-airplane" });
            imageList.Add(new SelectListItem { Text = "ion-link", Value = "ion-link" });
            imageList.Add(new SelectListItem { Text = "ion-paperclip", Value = "ion-paperclip" });
            imageList.Add(new SelectListItem { Text = "ion-compose", Value = "ion-compose" });
            imageList.Add(new SelectListItem { Text = "ion-briefcase", Value = "ion-briefcase" });
            imageList.Add(new SelectListItem { Text = "ion-medkit", Value = "ion-medkit" });
            imageList.Add(new SelectListItem { Text = "ion-at", Value = "ion-at" });
            imageList.Add(new SelectListItem { Text = "ion-pound", Value = "ion-pound" });
            imageList.Add(new SelectListItem { Text = "ion-quote", Value = "ion-quote" });
            imageList.Add(new SelectListItem { Text = "ion-cloud", Value = "ion-cloud" });
            imageList.Add(new SelectListItem { Text = "ion-upload", Value = "ion-upload" });
            imageList.Add(new SelectListItem { Text = "ion-more", Value = "ion-more" });
            imageList.Add(new SelectListItem { Text = "ion-grid", Value = "ion-grid" });
            imageList.Add(new SelectListItem { Text = "ion-calendar", Value = "ion-calendar" });
            imageList.Add(new SelectListItem { Text = "ion-clock", Value = "ion-clock" });
            imageList.Add(new SelectListItem { Text = "ion-compass", Value = "ion-compass" });
            imageList.Add(new SelectListItem { Text = "ion-pinpoint", Value = "ion-pinpoint" });
            imageList.Add(new SelectListItem { Text = "ion-pin", Value = "ion-pin" });
            imageList.Add(new SelectListItem { Text = "ion-navigate", Value = "ion-navigate" });
            imageList.Add(new SelectListItem { Text = "ion-location", Value = "ion-location" });
            imageList.Add(new SelectListItem { Text = "ion-map", Value = "ion-map" });
            imageList.Add(new SelectListItem { Text = "ion-lock-combination", Value = "ion-lock-combination" });
            imageList.Add(new SelectListItem { Text = "ion-locked", Value = "ion-locked" });
            imageList.Add(new SelectListItem { Text = "ion-unlocked", Value = "ion-unlocked" });
            imageList.Add(new SelectListItem { Text = "ion-key", Value = "ion-key" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-graph-up-right", Value = "ion-arrow-graph-up-right" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-graph-down-right", Value = "ion-arrow-graph-down-right" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-graph-up-left", Value = "ion-arrow-graph-up-left" });
            imageList.Add(new SelectListItem { Text = "ion-arrow-graph-down-left", Value = "ion-arrow-graph-down-left" });
            imageList.Add(new SelectListItem { Text = "ion-stats-bars", Value = "ion-stats-bars" });
            imageList.Add(new SelectListItem { Text = "ion-connection-bars", Value = "ion-connection-bars" });
            imageList.Add(new SelectListItem { Text = "ion-pie-graph", Value = "ion-pie-graph" });
            imageList.Add(new SelectListItem { Text = "ion-chatbubble", Value = "ion-chatbubble" });
            imageList.Add(new SelectListItem { Text = "ion-chatbubble-working", Value = "ion-chatbubble-working" });
            imageList.Add(new SelectListItem { Text = "ion-chatbubbles", Value = "ion-chatbubbles" });
            imageList.Add(new SelectListItem { Text = "ion-chatbox", Value = "ion-chatbox" });
            imageList.Add(new SelectListItem { Text = "ion-chatbox-working", Value = "ion-chatbox-working" });
            imageList.Add(new SelectListItem { Text = "ion-chatboxes", Value = "ion-chatboxes" });
            imageList.Add(new SelectListItem { Text = "ion-person", Value = "ion-person" });
            imageList.Add(new SelectListItem { Text = "ion-person-add", Value = "ion-person-add" });
            imageList.Add(new SelectListItem { Text = "ion-person-stalker", Value = "ion-person-stalker" });
            imageList.Add(new SelectListItem { Text = "ion-woman", Value = "ion-woman" });
            imageList.Add(new SelectListItem { Text = "ion-man", Value = "ion-man" });
            imageList.Add(new SelectListItem { Text = "ion-female", Value = "ion-female" });
            imageList.Add(new SelectListItem { Text = "ion-male", Value = "ion-male" });
            imageList.Add(new SelectListItem { Text = "ion-transgender", Value = "ion-transgender" });
            imageList.Add(new SelectListItem { Text = "ion-fork", Value = "ion-fork" });
            imageList.Add(new SelectListItem { Text = "ion-knife", Value = "ion-knife" });
            imageList.Add(new SelectListItem { Text = "ion-spoon", Value = "ion-spoon" });
            imageList.Add(new SelectListItem { Text = "ion-soup-can-outline", Value = "ion-soup-can-outline" });
            imageList.Add(new SelectListItem { Text = "ion-soup-can", Value = "ion-soup-can" });
            imageList.Add(new SelectListItem { Text = "ion-beer", Value = "ion-beer" });
            imageList.Add(new SelectListItem { Text = "ion-wineglass", Value = "ion-wineglass" });
            imageList.Add(new SelectListItem { Text = "ion-coffee", Value = "ion-coffee" });
            imageList.Add(new SelectListItem { Text = "ion-icecream", Value = "ion-icecream" });
            imageList.Add(new SelectListItem { Text = "ion-pizza", Value = "ion-pizza" });
            imageList.Add(new SelectListItem { Text = "ion-power", Value = "ion-power" });
            imageList.Add(new SelectListItem { Text = "ion-mouse", Value = "ion-mouse" });
            imageList.Add(new SelectListItem { Text = "ion-battery-full", Value = "ion-battery-full" });
            imageList.Add(new SelectListItem { Text = "ion-battery-half", Value = "ion-battery-half" });
            imageList.Add(new SelectListItem { Text = "ion-battery-low", Value = "ion-battery-low" });
            imageList.Add(new SelectListItem { Text = "ion-battery-empty", Value = "ion-battery-empty" });
            imageList.Add(new SelectListItem { Text = "ion-battery-charging", Value = "ion-battery-charging" });
            imageList.Add(new SelectListItem { Text = "ion-wifi", Value = "ion-wifi" });
            imageList.Add(new SelectListItem { Text = "ion-bluetooth", Value = "ion-bluetooth" });
            imageList.Add(new SelectListItem { Text = "ion-calculator", Value = "ion-calculator" });
            imageList.Add(new SelectListItem { Text = "ion-camera", Value = "ion-camera" });
            imageList.Add(new SelectListItem { Text = "ion-eye", Value = "ion-eye" });
            imageList.Add(new SelectListItem { Text = "ion-eye-disabled", Value = "ion-eye-disabled" });
            imageList.Add(new SelectListItem { Text = "ion-flash", Value = "ion-flash" });
            imageList.Add(new SelectListItem { Text = "ion-flash-off", Value = "ion-flash-off" });
            imageList.Add(new SelectListItem { Text = "ion-qr-scanner", Value = "ion-qr-scanner" });
            imageList.Add(new SelectListItem { Text = "ion-image", Value = "ion-image" });
            imageList.Add(new SelectListItem { Text = "ion-images", Value = "ion-images" });
            imageList.Add(new SelectListItem { Text = "ion-wand", Value = "ion-wand" });
            imageList.Add(new SelectListItem { Text = "ion-contrast", Value = "ion-contrast" });
            imageList.Add(new SelectListItem { Text = "ion-aperture", Value = "ion-aperture" });
            imageList.Add(new SelectListItem { Text = "ion-crop", Value = "ion-crop" });
            imageList.Add(new SelectListItem { Text = "ion-easel", Value = "ion-easel" });
            imageList.Add(new SelectListItem { Text = "ion-paintbrush", Value = "ion-paintbrush" });
            imageList.Add(new SelectListItem { Text = "ion-paintbucket", Value = "ion-paintbucket" });
            imageList.Add(new SelectListItem { Text = "ion-monitor", Value = "ion-monitor" });
            imageList.Add(new SelectListItem { Text = "ion-laptop", Value = "ion-laptop" });
            imageList.Add(new SelectListItem { Text = "ion-ipad", Value = "ion-ipad" });
            imageList.Add(new SelectListItem { Text = "ion-iphone", Value = "ion-iphone" });
            imageList.Add(new SelectListItem { Text = "ion-ipod", Value = "ion-ipod" });
            imageList.Add(new SelectListItem { Text = "ion-printer", Value = "ion-printer" });
            imageList.Add(new SelectListItem { Text = "ion-usb", Value = "ion-usb" });
            imageList.Add(new SelectListItem { Text = "ion-outlet", Value = "ion-outlet" });
            imageList.Add(new SelectListItem { Text = "ion-bug", Value = "ion-bug" });
            imageList.Add(new SelectListItem { Text = "ion-code", Value = "ion-code" });
            imageList.Add(new SelectListItem { Text = "ion-code-working", Value = "ion-code-working" });
            imageList.Add(new SelectListItem { Text = "ion-code-download", Value = "ion-code-download" });
            imageList.Add(new SelectListItem { Text = "ion-fork-repo", Value = "ion-fork-repo" });
            imageList.Add(new SelectListItem { Text = "ion-network", Value = "ion-network" });
            imageList.Add(new SelectListItem { Text = "ion-pull-request", Value = "ion-pull-request" });
            imageList.Add(new SelectListItem { Text = "ion-merge", Value = "ion-merge" });
            imageList.Add(new SelectListItem { Text = "ion-xbox", Value = "ion-xbox" });
            imageList.Add(new SelectListItem { Text = "ion-playstation", Value = "ion-playstation" });
            imageList.Add(new SelectListItem { Text = "ion-steam", Value = "ion-steam" });
            imageList.Add(new SelectListItem { Text = "ion-closed-captioning", Value = "ion-closed-captioning" });
            imageList.Add(new SelectListItem { Text = "ion-videocamera", Value = "ion-videocamera" });
            imageList.Add(new SelectListItem { Text = "ion-film-marker", Value = "ion-film-marker" });
            imageList.Add(new SelectListItem { Text = "ion-disc", Value = "ion-disc" });
            imageList.Add(new SelectListItem { Text = "ion-headphone", Value = "ion-headphone" });
            imageList.Add(new SelectListItem { Text = "ion-music-note", Value = "ion-music-note" });
            imageList.Add(new SelectListItem { Text = "ion-radio-waves", Value = "ion-radio-waves" });
            imageList.Add(new SelectListItem { Text = "ion-speakerphone", Value = "ion-speakerphone" });
            imageList.Add(new SelectListItem { Text = "ion-mic-a", Value = "ion-mic-a" });
            imageList.Add(new SelectListItem { Text = "ion-mic-b", Value = "ion-mic-b" });
            imageList.Add(new SelectListItem { Text = "ion-mic-c", Value = "ion-mic-c" });
            imageList.Add(new SelectListItem { Text = "ion-volume-high", Value = "ion-volume-high" });
            imageList.Add(new SelectListItem { Text = "ion-volume-medium", Value = "ion-volume-medium" });
            imageList.Add(new SelectListItem { Text = "ion-volume-low", Value = "ion-volume-low" });
            imageList.Add(new SelectListItem { Text = "ion-volume-mute", Value = "ion-volume-mute" });
            imageList.Add(new SelectListItem { Text = "ion-levels", Value = "ion-levels" });
            imageList.Add(new SelectListItem { Text = "ion-play", Value = "ion-play" });
            imageList.Add(new SelectListItem { Text = "ion-pause", Value = "ion-pause" });
            imageList.Add(new SelectListItem { Text = "ion-stop", Value = "ion-stop" });
            imageList.Add(new SelectListItem { Text = "ion-record", Value = "ion-record" });
            imageList.Add(new SelectListItem { Text = "ion-skip-forward", Value = "ion-skip-forward" });
            imageList.Add(new SelectListItem { Text = "ion-skip-backward", Value = "ion-skip-backward" });
            imageList.Add(new SelectListItem { Text = "ion-eject", Value = "ion-eject" });
            imageList.Add(new SelectListItem { Text = "ion-bag", Value = "ion-bag" });
            imageList.Add(new SelectListItem { Text = "ion-card", Value = "ion-card" });
            imageList.Add(new SelectListItem { Text = "ion-cash", Value = "ion-cash" });
            imageList.Add(new SelectListItem { Text = "ion-pricetag", Value = "ion-pricetag" });
            imageList.Add(new SelectListItem { Text = "ion-pricetags", Value = "ion-pricetags" });
            imageList.Add(new SelectListItem { Text = "ion-thumbsup", Value = "ion-thumbsup" });
            imageList.Add(new SelectListItem { Text = "ion-thumbsdown", Value = "ion-thumbsdown" });
            imageList.Add(new SelectListItem { Text = "ion-happy-outline", Value = "ion-happy-outline" });
            imageList.Add(new SelectListItem { Text = "ion-happy", Value = "ion-happy" });
            imageList.Add(new SelectListItem { Text = "ion-sad-outline", Value = "ion-sad-outline" });
            imageList.Add(new SelectListItem { Text = "ion-sad", Value = "ion-sad" });
            imageList.Add(new SelectListItem { Text = "ion-bowtie", Value = "ion-bowtie" });
            imageList.Add(new SelectListItem { Text = "ion-tshirt-outline", Value = "ion-tshirt-outline" });
            imageList.Add(new SelectListItem { Text = "ion-tshirt", Value = "ion-tshirt" });
            imageList.Add(new SelectListItem { Text = "ion-trophy", Value = "ion-trophy" });
            imageList.Add(new SelectListItem { Text = "ion-podium", Value = "ion-podium" });
            imageList.Add(new SelectListItem { Text = "ion-ribbon-a", Value = "ion-ribbon-a" });
            imageList.Add(new SelectListItem { Text = "ion-ribbon-b", Value = "ion-ribbon-b" });
            imageList.Add(new SelectListItem { Text = "ion-university", Value = "ion-university" });
            imageList.Add(new SelectListItem { Text = "ion-magnet", Value = "ion-magnet" });
            imageList.Add(new SelectListItem { Text = "ion-beaker", Value = "ion-beaker" });
            imageList.Add(new SelectListItem { Text = "ion-erlenmeyer-flask", Value = "ion-erlenmeyer-flask" });
            imageList.Add(new SelectListItem { Text = "ion-egg", Value = "ion-egg" });
            imageList.Add(new SelectListItem { Text = "ion-earth", Value = "ion-earth" });
            imageList.Add(new SelectListItem { Text = "ion-planet", Value = "ion-planet" });
            imageList.Add(new SelectListItem { Text = "ion-lightbulb", Value = "ion-lightbulb" });
            imageList.Add(new SelectListItem { Text = "ion-cube", Value = "ion-cube" });
            imageList.Add(new SelectListItem { Text = "ion-leaf", Value = "ion-leaf" });
            imageList.Add(new SelectListItem { Text = "ion-waterdrop", Value = "ion-waterdrop" });
            imageList.Add(new SelectListItem { Text = "ion-flame", Value = "ion-flame" });
            imageList.Add(new SelectListItem { Text = "ion-fireball", Value = "ion-fireball" });
            imageList.Add(new SelectListItem { Text = "ion-bonfire", Value = "ion-bonfire" });
            imageList.Add(new SelectListItem { Text = "ion-umbrella", Value = "ion-umbrella" });
            imageList.Add(new SelectListItem { Text = "ion-nuclear", Value = "ion-nuclear" });
            imageList.Add(new SelectListItem { Text = "ion-no-smoking", Value = "ion-no-smoking" });
            imageList.Add(new SelectListItem { Text = "ion-thermometer", Value = "ion-thermometer" });
            imageList.Add(new SelectListItem { Text = "ion-speedometer", Value = "ion-speedometer" });
            imageList.Add(new SelectListItem { Text = "ion-model-s", Value = "ion-model-s" });
            imageList.Add(new SelectListItem { Text = "ion-plane", Value = "ion-plane" });
            imageList.Add(new SelectListItem { Text = "ion-jet", Value = "ion-jet" });
            imageList.Add(new SelectListItem { Text = "ion-load-a", Value = "ion-load-a" });
            imageList.Add(new SelectListItem { Text = "ion-load-b", Value = "ion-load-b" });
            imageList.Add(new SelectListItem { Text = "ion-load-c", Value = "ion-load-c" });
            imageList.Add(new SelectListItem { Text = "ion-load-d", Value = "ion-load-d" });

            ViewBag.imageList=imageList;
            return View(value);
        }

        [HttpPost]
        public ActionResult UpdateSocialMedia(TblSocialMedia p)
        {
            var value = db.TblSocialMedia.Find(p.SocialMediaID);
            value.PlatformName = p.PlatformName;
            value.IconUrl = p.IconUrl;
            value.RedirectUrl = p.RedirectUrl;
            db.SaveChanges();
            return RedirectToAction("SocialMediaList");
        }
    }
}
